services:
  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis_data:
